# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127u8veUPfBpyXqc9YtLrLAhI8HNMuslg
"""

"""
main.py — cQuant Energy Analyst Programming Exercise
Author:   Daniela Guzman
Date:     May 2026

HOW TO RUN IN GOOGLE COLAB:
    1. Upload your CSV files
    2. Run all cells
"""


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import glob
import os

# ============================================================
# SETUP
# ============================================================
for folder in ["outputs/price_statistics", "outputs/volatility",
               "outputs/formattedSpotHistory", "outputs/hourlyShapeProfiles",
               "outputs/visualizations"]:
    os.makedirs(folder, exist_ok=True)

# Plot style
sns.set_theme(style="whitegrid", palette="husl")
COLORS = sns.color_palette("husl", 10)

# ============================================================
# TASK 1 — Load Data
# ============================================================
df = pd.concat([
    pd.read_csv("ERCOT_DA_Prices_2016.csv"),
    pd.read_csv("ERCOT_DA_Prices_2017.csv"),
    pd.read_csv("ERCOT_DA_Prices_2018.csv"),
    pd.read_csv("ERCOT_DA_Prices_2019.csv")
], ignore_index=True)

df['Date'] = pd.to_datetime(df['Date'])
print(f"Loaded {len(df):,} rows")

# ============================================================
# DATA VALIDATION
# ============================================================
expected_hours = pd.date_range(start=df['Date'].min(), end=df['Date'].max(), freq='h')
expected_rows  = len(expected_hours) * df['SettlementPoint'].nunique()
actual_rows    = len(df)
missing_rows   = expected_rows - actual_rows

print(f"\nExpected rows:  {expected_rows:,}")
print(f"Actual rows:    {actual_rows:,}")
print(f"Missing rows:   {missing_rows:,} ({missing_rows/expected_rows*100:.1f}%)")

missing_by_sp = (
    df.groupby("SettlementPoint")["Date"]
    .count().reset_index(name="ActualHours")
)
missing_by_sp["ExpectedHours"] = len(expected_hours)
missing_by_sp["MissingHours"]  = missing_by_sp["ExpectedHours"] - missing_by_sp["ActualHours"]
missing_by_sp["MissingPct"]    = (missing_by_sp["MissingHours"] / missing_by_sp["ExpectedHours"] * 100).round(2)

print(f"\nMissing hours per settlement point:")
print(missing_by_sp.to_string(index=False))

print(f"\nPrice summary:\n{df['Price'].describe().round(2).to_string()}")

df = df[df['Price'] > 0].copy()
print(f"\nClean data ready: {len(df):,} rows")

# These 4 missing hours are consistent across all settlement points
# and likely correspond to daylight saving time transitions
# HB_PAN exist only in 2019

# ============================================================
# TASK 2 — Monthly Average Price
# ============================================================
df_monthly = (
    df.groupby(["SettlementPoint", pd.Grouper(key="Date", freq="MS")])["Price"]
    .mean().reset_index()
)
df_monthly['Year']  = df_monthly['Date'].dt.year
df_monthly['Month'] = df_monthly['Date'].dt.month
df_monthly = df_monthly.rename(columns={"Price": "AveragePrice"})

print(f"\nMonthly averages computed")
print(df_monthly.head().to_string(index=False))

# ============================================================
# TASK 3 — Save Average Price
# ============================================================
df_monthly[["SettlementPoint", "Year", "Month", "AveragePrice"]].to_csv(
    "outputs/price_statistics/AveragePriceByMonth.csv", index=False)
print("\nAveragePriceByMonth.csv saved")


# ============================================================
# TASK 4 — Price Volatility - Hourly volatility is defined as the standard deviation in log returns of hourly prices.
# ============================================================
df_hubs = df[
    df["SettlementPoint"].str.startswith("HB_")
].copy()

# (log is only defined for positive values)
df_hubs = df_hubs[df_hubs["Price"] > 0]

df_hubs = df_hubs.sort_values(["SettlementPoint", "Date"]).reset_index(drop=True)
df_hubs["Year"]     = df_hubs["Date"].dt.year
df_hubs["TimeDiff"] = df_hubs.groupby("SettlementPoint")["Date"].diff().dt.total_seconds() / 3600
df_hubs["LogReturn"] = df_hubs.groupby("SettlementPoint")["Price"].transform(
    lambda s: np.log(s).diff())

# Set log return to NaN at gap points to avoid inflated volatility

df_hubs.loc[df_hubs["TimeDiff"] > 1, "LogReturn"] = np.nan
df_hubs = df_hubs.dropna(subset=["LogReturn"])

volatility_df = (
    df_hubs.groupby(["SettlementPoint", "Year"])["LogReturn"]
    .std().reset_index(name="HourlyVolatility")
)

print(f"\nVolatility computed")
print(volatility_df.to_string(index=False))

# ============================================================
# TASK 5 — Save Volatility
# ============================================================
volatility_df.to_csv("outputs/volatility/HourlyVolatilityByYear.csv", index=False)
print("\nHourlyVolatilityByYear.csv saved")

# ============================================================
# TASK 6 — Max Volatility per Year
# ============================================================
max_vol_df = (
    volatility_df.sort_values("HourlyVolatility", ascending=False)
    .drop_duplicates("Year").reset_index(drop=True)
)
print(f"\nMost volatile hub per year:")
print(max_vol_df.to_string(index=False))

max_vol_df.to_csv("outputs/volatility/MaxVolatilityByYear.csv", index=False)
print("\nMaxVolatilityByYear.csv saved")

# ============================================================
# TASK 7 — Spot Price History (Wide Format X1..X24)
# ============================================================
df['Day']  = df['Date'].dt.date
df['Hour'] = df['Date'].dt.hour

pivot = df.pivot_table(index=["SettlementPoint", "Day"], columns="Hour", values="Price")
pivot.columns = [f"X{h+1}" for h in pivot.columns]
pivot.reset_index(inplace=True)
pivot.rename(columns={"Day": "Date", "SettlementPoint": "Variable"}, inplace=True)

for sp, g in pivot.groupby("Variable", sort=False):
    g.to_csv(f"outputs/formattedSpotHistory/spot_{sp}.csv", index=False)
print(f"\nSpot history saved for {pivot['Variable'].nunique()} settlement points")

# ============================================================
# VISUALIZATIONS
# ============================================================
df_plot = df_monthly.copy()
df_plot["Date"] = pd.to_datetime(df_plot[["Year", "Month"]].assign(Day=1))

# --- Plot 1: Hub Average Price by Month ---
fig, ax = plt.subplots(figsize=(14, 6))
hub_data = df_plot[df_plot["SettlementPoint"].str.startswith("HB_")]
for i, (sp, g) in enumerate(hub_data.groupby("SettlementPoint")):
    ax.plot(g["Date"], g["AveragePrice"], label=sp, linewidth=2, color=COLORS[i], marker="o", markersize=3)
ax.set_title("Settlement Hub — Average Monthly Price (2016–2019)", fontsize=15, fontweight="bold", pad=15)
ax.set_ylabel("Average Price ($/MWh)", fontsize=12)
ax.set_xlabel("")
ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('$%.0f'))
ax.legend(title="Settlement Hub", bbox_to_anchor=(1.01, 1), loc="upper left", fontsize=10)
ax.tick_params(axis='x', labelrotation=45)
sns.despine()
plt.tight_layout()
plt.savefig("outputs/visualizations/SettlementHubAveragePriceByMonth.png", dpi=175, bbox_inches="tight")
plt.show()

# --- Plot 2: Load Zone Average Price by Month ---
fig, ax = plt.subplots(figsize=(14, 6))
lz_data = df_plot[df_plot["SettlementPoint"].str.startswith("LZ_")]
for i, (sp, g) in enumerate(lz_data.groupby("SettlementPoint")):
    ax.plot(g["Date"], g["AveragePrice"], label=sp, linewidth=2, color=COLORS[i], marker="o", markersize=3)
ax.set_title("Load Zone — Average Monthly Price (2016–2019)", fontsize=15, fontweight="bold", pad=15)
ax.set_ylabel("Average Price ($/MWh)", fontsize=12)
ax.set_xlabel("")
ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('$%.0f'))
ax.legend(title="Load Zone", bbox_to_anchor=(1.01, 1), loc="upper left", fontsize=10)
ax.tick_params(axis='x', labelrotation=45)
sns.despine()
plt.tight_layout()
plt.savefig("outputs/visualizations/LoadZoneAveragePriceByMonth.png", dpi=175, bbox_inches="tight")
plt.show()

# --- Plot 3a: Volatility by Hub and Year - Bar Chart ---
fig, ax = plt.subplots(figsize=(12, 6))
sns.barplot(data=volatility_df, x="Year", y="HourlyVolatility",
            hue="SettlementPoint", palette="husl", ax=ax, edgecolor="white", linewidth=0.5)
ax.set_title("Hourly Volatility by Settlement Hub and Year", fontsize=15, fontweight="bold", pad=15)
ax.set_ylabel("Volatility (Std Dev of Log Returns)", fontsize=12)
ax.set_xlabel("Year", fontsize=12)
ax.legend(title="Settlement Hub", bbox_to_anchor=(1.01, 1), loc="upper left", fontsize=10)
sns.despine()
plt.tight_layout()
plt.savefig("outputs/visualizations/HourlyVolatilityByYear.png", dpi=175, bbox_inches="tight")
plt.show()

# --- Plot 3b: Volatility Heatmap - easier to spot patterns across hubs and years ---
volatility_pivot = volatility_df.pivot(index="SettlementPoint", columns="Year", values="HourlyVolatility")

fig, ax = plt.subplots(figsize=(10, 6))
sns.heatmap(volatility_pivot, annot=True, fmt=".3f", cmap="YlOrRd",
            linewidths=0.5, ax=ax, cbar_kws={"label": "Volatility (Std Dev of Log Returns)"})
ax.set_title("Hourly Volatility Heatmap by Settlement Hub and Year", fontsize=15, fontweight="bold", pad=15)
ax.set_xlabel("Year", fontsize=12)
ax.set_ylabel("")
plt.tight_layout()
plt.savefig("outputs/visualizations/HourlyVolatilityHeatmap.png", dpi=175, bbox_inches="tight")
plt.show()

# --- Plot 4: Price Distribution by Hub ---
# Cap y-axis at 95th percentile to show the bulk of the distribution clearly
# Outliers above this threshold are noted in the title
hub_prices = df[df["SettlementPoint"].str.startswith("HB_")].copy()
price_cap = hub_prices["Price"].quantile(0.95)

fig, ax = plt.subplots(figsize=(14, 6))
sns.boxplot(data=hub_prices, x="SettlementPoint", y="Price",
            palette="husl", ax=ax,
            flierprops=dict(marker=".", markersize=2, alpha=0.2),
            order=sorted(hub_prices["SettlementPoint"].unique()))
ax.set_ylim(0, price_cap)
ax.set_title(f"Price Distribution by Settlement Hub (2016–2019)\nY-axis capped at 95th percentile (${price_cap:.0f}/MWh) for readability",
             fontsize=13, fontweight="bold", pad=15)
ax.set_ylabel("Price ($/MWh)", fontsize=12)
ax.set_xlabel("")
ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('$%.0f'))
ax.tick_params(axis='x', labelrotation=15)
sns.despine()
plt.tight_layout()
plt.savefig("outputs/visualizations/HubPriceDistribution.png", dpi=175, bbox_inches="tight")
plt.show()

# ============================================================
# SHAPE PROFILES
# ============================================================
df["Month"]     = df["Date"].dt.month
df["DayOfWeek"] = df["Date"].dt.dayofweek
df["Hour"]      = df["Date"].dt.hour

hourly_avg = df.groupby(['SettlementPoint', 'Month', 'DayOfWeek', 'Hour'])["Price"].mean().reset_index()
hourly_avg["HourlyShape"] = (
    hourly_avg["Price"] /
    hourly_avg.groupby(['SettlementPoint', 'Month', 'DayOfWeek'])["Price"].transform("mean")
)
pivot2 = hourly_avg.pivot_table(
    index=["SettlementPoint", "Month", "DayOfWeek"], columns="Hour", values="HourlyShape")
pivot2.columns = [f"X{h+1}" for h in pivot2.columns]
pivot2.reset_index(inplace=True)

for sp, g in pivot2.groupby("SettlementPoint"):
    g.to_csv(f"outputs/hourlyShapeProfiles/profile_{sp}.csv", index=False)
print(f"Shape profiles saved for {pivot2['SettlementPoint'].nunique()} settlement points")

# ============================================================
# DOWNLOAD ALL OUTPUTS
# ============================================================
from google.colab import files

for folder in ["outputs/price_statistics", "outputs/volatility",
               "outputs/visualizations", "outputs/hourlyShapeProfiles",
               "outputs/formattedSpotHistory"]:
    for f in os.listdir(folder):
        files.download(f"{folder}/{f}")

# ============================================================
# BONUS — Open-Ended Analysis
#
# Power prices alone can reveal a great deal about a region's
# energy dynamics. Without knowing exact supply or demand figures,
# price patterns expose structural strengths and weaknesses of
# each locality — from grid congestion and fuel mix to weather
# sensitivity and infrastructure constraints.
# Below we explore how each settlement hub behaves across the
# four seasons, revealing where and when price spikes concentrate.
# ============================================================

df["Hour"]      = df["Date"].dt.hour
df["DayOfWeek"] = df["Date"].dt.dayofweek
df["Year"]      = df["Date"].dt.year
df["Month"]     = df["Date"].dt.month

def get_season(month):
    if month in [12, 1, 2]:  return "Winter"
    elif month in [3, 4, 5]: return "Spring"
    elif month in [6, 7, 8]: return "Summer"
    else:                     return "Fall"

df["Season"] = df["Month"].apply(get_season)

season_order  = ["Winter", "Spring", "Summer", "Fall"]
season_colors = {"Winter": "#3498db", "Spring": "#2ecc71",
                 "Summer": "#e74c3c", "Fall":   "#e67e22"}

hubs = sorted(df[df["SettlementPoint"].str.startswith("HB_")]["SettlementPoint"].unique())
df_hubs = df[df["SettlementPoint"].str.startswith("HB_")].copy()

# ---- Plot 1: Average price by hub and season ----
# Shows which hubs are most expensive in each season
# revealing seasonal supply/demand imbalances per locality
seasonal_avg = (
    df_hubs.groupby(["SettlementPoint", "Season"])["Price"]
    .mean().reset_index()
)
seasonal_avg["Hub"] = seasonal_avg["SettlementPoint"].str.replace("HB_", "")

fig, axes = plt.subplots(1, 4, figsize=(18, 6), sharey=True)
for i, season in enumerate(season_order):
    data = seasonal_avg[seasonal_avg["Season"] == season].sort_values("Price", ascending=False)
    axes[i].barh(data["Hub"], data["Price"],
                 color=season_colors[season], alpha=0.85, edgecolor="white")
    axes[i].set_title(season, fontsize=13, fontweight="bold", color=season_colors[season])
    axes[i].set_xlabel("Avg Price ($/MWh)", fontsize=10)
    axes[i].xaxis.set_major_formatter(mticker.FormatStrFormatter('$%.0f'))
    if i == 0:
        axes[i].set_ylabel("Settlement Hub", fontsize=11)
    sns.despine(ax=axes[i])

fig.suptitle("Average Price by Settlement Hub and Season\nWhich hubs are most expensive and when?",
             fontsize=14, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig("outputs/visualizations/HubAveragePriceBySeason.png", dpi=175, bbox_inches="tight")
plt.show()

# ---- Plot 2: Price spike magnitude by hub and season ----
# A spike is defined as any hour above the 95th percentile
# We look at HOW MUCH prices spike, not just how often
# This reveals which localities are most vulnerable to extreme prices
spike_threshold = df_hubs["Price"].quantile(0.95)
df_spikes = df_hubs[df_hubs["Price"] > spike_threshold].copy()

spike_magnitude = (
    df_spikes.groupby(["SettlementPoint", "Season"])["Price"]
    .mean().reset_index(name="AvgSpikePrice")
)
spike_magnitude["Hub"] = spike_magnitude["SettlementPoint"].str.replace("HB_", "")

spike_pivot = spike_magnitude.pivot(index="Hub", columns="Season", values="AvgSpikePrice")
spike_pivot = spike_pivot[season_order]

fig, ax = plt.subplots(figsize=(12, 7))
sns.heatmap(spike_pivot, annot=True, fmt=".0f", cmap="YlOrRd",
            linewidths=0.5, ax=ax,
            cbar_kws={"label": "Average Spike Price ($/MWh)"},
            annot_kws={"size": 11})
ax.set_title(f"Average Spike Price by Hub and Season\n(Spike = price above 95th percentile: ${spike_threshold:.0f}/MWh)\nHigher values = more severe price spikes",
             fontsize=13, fontweight="bold", pad=15)
ax.set_xlabel("")
ax.set_ylabel("")
plt.tight_layout()
plt.savefig("outputs/visualizations/HubSpikeMagnitudeBySeason.png", dpi=175, bbox_inches="tight")
plt.show()

# ---- Plot 3: Spike frequency by hub and season ----
# How often does each hub spike in each season?
# Combined with Plot 2 this gives a full picture:
# frequent + large spikes = structurally weak locality
spike_freq = (
    df_hubs.groupby(["SettlementPoint", "Season"])
    .apply(lambda x: (x["Price"] > spike_threshold).mean())
    .reset_index(name="SpikeFrequency")
)
spike_freq["Hub"] = spike_freq["SettlementPoint"].str.replace("HB_", "")

freq_pivot = spike_freq.pivot(index="Hub", columns="Season", values="SpikeFrequency")
freq_pivot = freq_pivot[season_order]

fig, ax = plt.subplots(figsize=(12, 7))
sns.heatmap(freq_pivot, annot=True, fmt=".1%", cmap="YlOrRd",
            linewidths=0.5, ax=ax,
            cbar_kws={"label": "Spike Frequency (% of hours)"},
            annot_kws={"size": 11})
ax.set_title("Price Spike Frequency by Hub and Season\n(% of hours above 95th percentile)\nHigher values = spikes happen more often",
             fontsize=13, fontweight="bold", pad=15)
ax.set_xlabel("")
ax.set_ylabel("")
plt.tight_layout()
plt.savefig("outputs/visualizations/HubSpikeFrequencyBySeason.png", dpi=175, bbox_inches="tight")
plt.show()

# ---- Plot 4: Intraday spike pattern by season ----
# At what time of day do spikes happen in each season?
# This reveals the structural drivers:
# Summer afternoon spikes = AC demand
# Winter morning spikes = heating demand
# These patterns are critical for scheduling and hedging decisions
spike_hour = (
    df_hubs[df_hubs["Price"] > spike_threshold]
    .groupby(["Season", "Hour"])["Price"]
    .count().reset_index(name="SpikeCount")
)
total_by_season = df_hubs.groupby("Season")["Price"].count().reset_index(name="Total")
spike_hour = spike_hour.merge(total_by_season, on="Season")
spike_hour["SpikeRate"] = spike_hour["SpikeCount"] / spike_hour["Total"]

fig, axes = plt.subplots(1, 4, figsize=(18, 5), sharey=True)
for i, season in enumerate(season_order):
    data = spike_hour[spike_hour["Season"] == season]
    axes[i].fill_between(data["Hour"], data["SpikeRate"],
                         color=season_colors[season], alpha=0.7)
    axes[i].plot(data["Hour"], data["SpikeRate"],
                 color=season_colors[season], linewidth=2)
    axes[i].set_title(season, fontsize=13, fontweight="bold", color=season_colors[season])
    axes[i].set_xlabel("Hour of Day", fontsize=10)
    axes[i].set_xticks([0, 6, 12, 18, 23])
    axes[i].yaxis.set_major_formatter(mticker.PercentFormatter(xmax=1, decimals=1))
    if i == 0:
        axes[i].set_ylabel("Spike Rate", fontsize=11)
    sns.despine(ax=axes[i])

fig.suptitle("Intraday Price Spike Pattern by Season\nAt what time of day do spikes concentrate?",
             fontsize=14, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig("outputs/visualizations/IntradaySpikePatternBySeason.png", dpi=175, bbox_inches="tight")
plt.show()

print("Open-ended analysis complete")

# Define peak vs off-peak hours
# Peak: weekdays 7am-10pm | Off-peak: everything else
df["Hour"]      = df["Date"].dt.hour
df["DayOfWeek"] = df["Date"].dt.dayofweek
df["Year"]      = df["Date"].dt.year
df["Month"]     = df["Date"].dt.month

df["PeakType"] = "Off-Peak"
df.loc[
    (df["DayOfWeek"] < 5) & (df["Hour"] >= 7) & (df["Hour"] <= 22),
    "PeakType"
] = "Peak"

print("Peak vs Off-Peak hour distribution:")
print(df["PeakType"].value_counts())

# ---- Plot 1: Peak vs Off-Peak average price by year ----
# This shows whether the premium for peak hours changed over time
peak_avg = (
    df[df["SettlementPoint"] == "HB_HOUSTON"]
    .groupby(["Year", "PeakType"])["Price"]
    .mean().reset_index()
)

fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=peak_avg, x="Year", y="Price", hue="PeakType",
            palette={"Peak": "#e74c3c", "Off-Peak": "#3498db"}, ax=ax)
ax.set_title("HB_HOUSTON — Average Peak vs Off-Peak Price by Year",
             fontsize=14, fontweight="bold", pad=15)
ax.set_ylabel("Average Price ($/MWh)", fontsize=12)
ax.set_xlabel("Year", fontsize=12)
ax.legend(title="Period")
sns.despine()
plt.tight_layout()
plt.savefig("outputs/visualizations/PeakVsOffPeakByYear.png", dpi=175, bbox_inches="tight")
plt.show()

# ---- Plot 2: Average hourly price curve by season ----
# This shows the intraday price shape and how it varies by season
# Season: Winter (Dec-Feb), Spring (Mar-May), Summer (Jun-Aug), Fall (Sep-Nov)
def get_season(month):
    if month in [12, 1, 2]:  return "Winter"
    elif month in [3, 4, 5]: return "Spring"
    elif month in [6, 7, 8]: return "Summer"
    else:                     return "Fall"

df["Season"] = df["Month"].apply(get_season)

hourly_season = (
    df[df["SettlementPoint"] == "HB_HOUSTON"]
    .groupby(["Season", "Hour"])["Price"]
    .mean().reset_index()
)

season_order  = ["Winter", "Spring", "Summer", "Fall"]
season_colors = {"Winter": "#3498db", "Spring": "#2ecc71",
                 "Summer": "#e74c3c", "Fall":   "#e67e22"}

fig, ax = plt.subplots(figsize=(12, 5))
for season in season_order:
    data = hourly_season[hourly_season["Season"] == season]
    ax.plot(data["Hour"], data["Price"], label=season,
            color=season_colors[season], linewidth=2.5, marker="o", markersize=4)
ax.set_title("HB_HOUSTON — Average Intraday Price Curve by Season",
             fontsize=14, fontweight="bold", pad=15)
ax.set_ylabel("Average Price ($/MWh)", fontsize=12)
ax.set_xlabel("Hour of Day", fontsize=12)
ax.set_xticks(range(0, 24))
ax.legend(title="Season")
sns.despine()
plt.tight_layout()
plt.savefig("outputs/visualizations/IntradayPriceCurveBySeason.png", dpi=175, bbox_inches="tight")
plt.show()

# ---- Plot 3: Price spike analysis ----
# A price spike is defined here as any hour where price > 99th percentile
# Spikes are relevant for risk management and hedging strategies
spike_threshold = df["Price"].quantile(0.99)
df["IsSpike"] = df["Price"] > spike_threshold

spikes_by_hour = (
    df[df["SettlementPoint"] == "HB_HOUSTON"]
    .groupby("Hour")["IsSpike"]
    .mean()
    .reset_index(name="SpikeFrequency")
)

fig, ax = plt.subplots(figsize=(12, 5))
sns.barplot(data=spikes_by_hour, x="Hour", y="SpikeFrequency",
            color="#e74c3c", ax=ax)
ax.set_title(f"HB_HOUSTON — Price Spike Frequency by Hour\n(Spike = price above 99th percentile: ${spike_threshold:.0f}/MWh)",
             fontsize=14, fontweight="bold", pad=15)
ax.set_ylabel("Spike Frequency", fontsize=12)
ax.set_xlabel("Hour of Day", fontsize=12)
ax.yaxis.set_major_formatter(mticker.PercentFormatter(xmax=1, decimals=1))
sns.despine()
plt.tight_layout()
plt.savefig("outputs/visualizations/PriceSpikeFrequencyByHour.png", dpi=175, bbox_inches="tight")
plt.show()

print("Open-ended analysis complete")